spring:
    application:
        name: flightInfo
    data:
        mongodb:
            uri: mongodb://localhost:27017/flightdb
    datasource:
        url: jdbc:mysql://localhost:3307/flightdb
        username: root
        password: root
management:
    server:
        port: ${MANAGEMENT_PORT:9000}
    endpoints:
        web:
            exposure:
                include: health, prometheus # , shutdown
 #           base-path: "/"
  #          path-mapping:
   #             prometheus: "metrics"
   #     endpoint:
   #         shutdown:
   #             enabled: true
   #         health:
   #             show-details: always





