spring:
    application:
        name: flightInfo
    data:
        mongodb:
            uri: mongodb://localhost:27017/flightdb

management:
    server:
        port: ${MANAGEMENT_PORT:9000} # http://localhost:9000/actuator/health
    endpoints:
        web:
            exposure:
                include: health, prometheus # , shutdown
 #           base-path: "/"
  #          path-mapping:
   #             prometheus: "metrics"
   #     endpoint:
   #         shutdown:
   #             enabled: true
   #         health:
   #             show-details: always





